name: CI

on:
  push:
    branches: [ "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.13.5]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e ".[dev]"

      - name: Install pre-commit hooks
        run: pre-commit install --install-hooks

      - name: Run pre-commit (linters/typecheck/format)
        run: pre-commit run --all-files

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
