name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install all dependencies (including dev)
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Run pre-commit hooks
        run: |
          poetry run pre-commit install --install-hooks
          poetry run pre-commit run --all-files

      - name: Run tests
        run: |
          poetry run pytest --maxfail=1 --disable-warnings -q

